sudo: required

dist: xenial

language: python

matrix:
  include:
    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes -c pytorch pytorch-nightly
        - cd test-osx-issue
      script:
        - python setup.py develop
        - python run.py
